@extends('layouts.public')
@php($company = \App\Support\Company::all())
@section('content')
<section class="future-hero">
    <div class="hero-orbit orbit-one" aria-hidden="true"></div><div class="hero-orbit orbit-two" aria-hidden="true"></div>
    <div class="container future-grid">
        <div class="future-copy">
            <span class="overline"><span class="live-dot"></span> CONHECIMENTO QUE TRANSFORMA NEGÓCIOS</span>
            <h1>@if(empty($company['hero_title']) || $company['hero_title'] === 'O próximo passo do seu negócio começa aqui.')O futuro do<br>seu negócio<br><em>começa agora.</em>@else{{ $company['hero_title'] }}@endif</h1>
            <p>{{ $company['hero_text'] ?? 'Contabilidade, estratégia e consultoria para transformar os desafios de hoje nas conquistas de amanhã.' }}</p>
            <div class="actions"><a class="button" href="/orcamento">Vamos construir juntos <span>↗</span></a><a class="hero-discover" href="#solucoes"><span class="play-icon">↓</span> Explore nossas soluções</a></div>
            <div class="hero-signature"><span class="signature-line"></span><span>O futuro em suas mãos.<br><strong>A Cotech ao seu lado.</strong></span></div>
        </div>
        <div class="future-art" aria-label="Contabilidade, estratégia e gestão conectadas ao seu negócio">
            <div class="art-grid" aria-hidden="true"></div><div class="orbit-ring ring-a" aria-hidden="true"></div><div class="orbit-ring ring-b" aria-hidden="true"></div>
            <div class="brand-planet"><img src="/images/logo.jpeg" alt="Cotech — O futuro em suas mãos" width="230" height="230"></div>
            <div class="floating-note note-one"><span class="note-icon">↗</span><div><small>MAIS DIREÇÃO</small><strong>Estratégia para crescer</strong></div></div>
            <div class="floating-note note-two"><span class="note-icon">▥</span><div><small>MAIS CLAREZA</small><strong>Seus números fazem sentido.</strong><div class="mini-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div>
            <div class="floating-note note-three"><span class="status-dot"></span> Pessoas. Negócios. Possibilidades.</div>
            <span class="art-caption">CONECTAMOS O PRESENTE AO SEU PRÓXIMO PASSO</span>
        </div>
    </div>
    <div class="container hero-bottom"><span>CONTABILIDADE COM VISÃO DE FUTURO</span><a href="#solucoes">Continue explorando <span>↓</span></a></div>
</section>
<div class="brand-ribbon" aria-label="Contabilidade, planejamento e consultoria"><div class="ribbon-track" aria-hidden="true">@for($i=0;$i<4;$i++)<span>CONTABILIDADE</span><b>✳</b><span>ESTRATÉGIA</span><b>✳</b><span>CONSULTORIA</span><b>✳</b><span>SEU PRÓXIMO PASSO</span><b>✳</b>@endfor</div></div>
<section class="section solutions-section" id="solucoes"><div class="container">
    <div class="section-head" data-reveal><div><span class="eyebrow">01 / SOLUÇÕES QUE MOVEM</span><h2>Você cuida da visão.<br><span class="ink-blue">Nós ajudamos no caminho.</span></h2></div><div class="section-aside"><p>O apoio certo para cada momento do seu negócio. Conheça o que podemos construir juntos.</p><a class="text-link" href="/servicos">Explorar todos os serviços <span>↗</span></a></div></div>
    <div class="solution-grid">@forelse($services as $service)<a class="solution-card" href="/servicos/{{ $service->slug }}" data-reveal><div class="solution-top"><span class="solution-icon" aria-hidden="true">@if($loop->index % 3 === 0)▥@elseif($loop->index % 3 === 1)↗@else◎@endif</span><span class="solution-number">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span></div><h3>{{ $service->title }}</h3><p>{{ $service->summary }}</p><div class="solution-link">Descubra as possibilidades <span>↗</span></div></a>@empty<div class="empty">Conte o que precisa. Nossa equipe ajuda a encontrar a solução.</div>@endforelse</div>
</div></section>
<section class="section about-section" id="sobre"><div class="container about-grid">
    <div class="about-visual" data-reveal><div class="about-image"><img src="/images/fernando.png" alt="Fernando Kiosa, CEO da Cotech" loading="lazy" width="600" height="650"><div class="photo-caption"><span>UMA VISÃO. MUITAS POSSIBILIDADES.</span><strong>O próximo capítulo<br>é construído juntos.</strong></div></div><div class="about-stamp"><span>COTECH</span><strong>↗</strong><span>SEMPRE EM FRENTE</span></div></div>
    <div class="about-copy" data-reveal><span class="eyebrow">02 / PROXIMIDADE QUE FAZ A DIFERENÇA</span><h2>Mais que uma empresa.<br><span class="ink-blue">Uma parceria de verdade.</span></h2><p>Acreditamos que por trás de cada número existe uma história, uma decisão e um futuro para construir.</p><p class="muted">Por isso, unimos conhecimento e proximidade para entender o seu momento, organizar suas prioridades e transformar planos em próximos passos.</p><div class="value-line"><span>01</span><div><h3>Escuta antes da solução.</h3><p>Seu contexto é o nosso ponto de partida.</p></div></div><div class="value-line"><span>02</span><div><h3>Clareza em cada decisão.</h3><p>Informações que ajudam você a seguir em frente.</p></div></div><a class="button blue-button" href="/orcamento">Conheça a sua próxima parceria ↗</a></div>
</div></section>
<section class="section process-section"><div class="container"><div class="section-head" data-reveal><div><span class="eyebrow">03 / DO PRIMEIRO OLÁ AO PRÓXIMO PASSO</span><h2>Avançar pode ser<br>mais simples.</h2></div><p class="section-aside">Uma conversa abre o caminho.<br>Uma parceria ajuda a percorrê-lo.</p></div>
<div class="process-layout" data-reveal><div class="process-tabs" role="tablist" aria-label="Como trabalhamos" aria-orientation="vertical">@foreach(['Uma conversa que importa','Um plano para sua realidade','Uma parceria para avançar'] as $label)<button class="process-tab {{ $loop->first ? 'selected' : '' }}" id="step-tab-{{ $loop->index }}" role="tab" aria-selected="{{ $loop->first ? 'true' : 'false' }}" aria-controls="step-panel-{{ $loop->index }}" tabindex="{{ $loop->first ? 0 : -1 }}" data-step="{{ $loop->index }}"><span>0{{ $loop->iteration }}</span>{{ $label }}<b>↗</b></button>@endforeach</div>
<div class="process-panels">@foreach([['Tudo começa com você.','Conte seus desafios, suas ideias e o que espera para o seu negócio. Ouvimos com atenção para entender onde podemos fazer a diferença.','Vamos conversar','/orcamento'],['O seu momento define o caminho.','Organizamos as necessidades e propomos um escopo de trabalho com prioridades claras e soluções adequadas à sua realidade.','Conheça nossas soluções','/servicos'],['Seguimos juntos no próximo passo.','Acompanhamos o trabalho com comunicação próxima e informações claras para apoiar suas decisões ao longo do caminho.','Comece essa parceria','/orcamento']] as [$title,$body,$label,$url])<div class="process-panel" id="step-panel-{{ $loop->index }}" role="tabpanel" aria-labelledby="step-tab-{{ $loop->index }}" tabindex="0" @if(!$loop->first) hidden @endif><span class="process-big-number" aria-hidden="true">0{{ $loop->iteration }}</span><span class="eyebrow">NOSSO JEITO DE TRABALHAR</span><h3>{{ $title }}</h3><p>{{ $body }}</p><a class="text-link" href="{{ $url }}">{{ $label }} ↗</a></div>@endforeach</div></div>
</div></section>
@if($team->isNotEmpty())<section class="section team-section"><div class="container"><div class="section-head" data-reveal><div><span class="eyebrow">04 / QUEM CONSTRÓI COM VOCÊ</span><h2>Conhecimento tem nome.<br><span class="ink-blue">E gente por trás.</span></h2></div><p class="section-aside">Pessoas comprometidas com a próxima etapa do seu negócio.</p></div><div class="team-grid">@foreach($team as $person)<article class="person-card" data-reveal><div class="person-photo">@if($person->image)<img src="{{ $person->image }}" alt="{{ $person->title }}" loading="lazy" width="600" height="550">@endif<span class="person-mark" aria-hidden="true">↗</span></div><div class="person-info"><h3>{{ $person->title }}</h3><span>{{ $person->summary }}</span></div></article>@endforeach</div></div></section>@endif
@if($posts->isNotEmpty())<section class="section insights-section"><div class="container"><div class="section-head" data-reveal><div><span class="eyebrow">05 / IDEIAS QUE ABREM CAMINHOS</span><h2>Seu próximo insight<br>pode começar aqui.</h2></div><a class="text-link" href="/blog">Explore os conteúdos <span>↗</span></a></div><div class="insight-grid">@foreach($posts as $post)<article class="insight-card" data-reveal><a class="insight-cover cover-{{ $loop->index % 3 }}" href="/blog/{{ $post->slug }}" tabindex="-1" aria-hidden="true">@if($post->image && !in_array($post->image,['/images/contabilidade.jpeg','/images/planejamento.jpeg','/images/contadores.jpeg']))<img class="editorial-photo" src="{{ $post->image }}" alt="">@else<span>COTECH / EM PERSPECTIVA</span><div class="editorial-shape shape-{{ $loop->index % 3 }}"></div><b>{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</b><span class="cover-arrow">↗</span>@endif</a><div class="insight-meta"><span>{{ $post->category ?: 'NEGÓCIOS & ESTRATÉGIA' }}</span><span>{{ ($post->published_at ?? $post->created_at)->format('d.m.Y') }}</span></div><h3><a href="/blog/{{ $post->slug }}">{{ $post->title }}</a></h3><p>{{ $post->summary }}</p><a class="text-link" href="/blog/{{ $post->slug }}">Ler conteúdo ↗</a></article>@endforeach</div></div></section>@endif
@if($testimonials->isNotEmpty())<section class="section"><div class="container"><span class="eyebrow">CONFIANÇA QUE SE CONSTRÓI</span><h2>Quem caminha com a gente.</h2><div class="grid">@foreach($testimonials as $item)<blockquote class="card quote-card" data-reveal><span class="quote-mark">“</span><p>{{ $item->body }}</p><strong>{{ $item->title }}</strong><div class="muted">{{ $item->summary }}</div></blockquote>@endforeach</div></div></section>@endif
@if($certifications->isNotEmpty())<section class="section"><div class="container"><h2>Certificações</h2><div class="grid">@foreach($certifications as $item)<div class="card" data-reveal><h3>{{ $item->title }}</h3><p>{{ $item->summary }}</p></div>@endforeach</div></div></section>@endif
@if($banners->isNotEmpty())<section class="section"><div class="container grid">@foreach($banners as $item)<article class="card image-card" data-reveal>@if($item->image)<img loading="lazy" src="{{ $item->image }}" alt="{{ $item->title }}">@endif<div class="card-body"><h3>{{ $item->title }}</h3><p>{{ $item->summary }}</p><a class="text-link" href="/orcamento">Saiba mais ↗</a></div></article>@endforeach</div></section>@endif
@if($faqs->isNotEmpty())<section class="section faq-section"><div class="container faq-grid"><div data-reveal><span class="eyebrow">VAMOS ESCLARECER?</span><h2>Boas perguntas.<br><span class="ink-blue">Caminhos mais claros.</span></h2><p class="muted">Ainda tem alguma dúvida?<br>A nossa equipe está aqui para conversar.</p><a class="text-link" href="/orcamento">Fale com a Cotech ↗</a></div><div class="faq-list" data-reveal>@foreach($faqs as $faq)<details name="cotech-faq"><summary><span class="faq-number">0{{ $loop->iteration }}</span>{{ $faq->title }}<span class="faq-toggle" aria-hidden="true">+</span></summary><p>{{ $faq->body }}</p></details>@endforeach</div></div></section>@endif
<section class="final-cta"><div class="container" data-reveal><span class="overline">SEU FUTURO NÃO PRECISA ESPERAR.</span><h2>Vamos dar o<br><em>próximo passo?</em></h2><div class="cta-bottom"><p>Você traz os planos.<br>A gente ajuda a construir o caminho.</p><a class="button" href="/orcamento">Comece essa conversa <span>↗</span></a></div></div><div class="cta-orbit" aria-hidden="true"></div></section>
@endsection
