<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('users', fn(Blueprint $t) => $t->string('role')->default('attendant'));
  Schema::create('contents', function(Blueprint $t) { $t->id(); $t->string('type')->index(); $t->string('title'); $t->string('slug')->unique(); $t->string('category')->nullable(); $t->text('summary')->nullable(); $t->longText('body')->nullable(); $t->string('image')->nullable(); $t->string('seo_title')->nullable(); $t->text('meta_description')->nullable(); $t->boolean('active')->default(false); $t->boolean('authorized')->default(false); $t->timestamp('published_at')->nullable(); $t->timestamp('ends_at')->nullable(); $t->integer('sort')->default(0); $t->json('extra')->nullable(); $t->timestamps(); });
  Schema::create('lead_statuses', function(Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->string('color')->default('#6366f1'); $t->string('outcome')->nullable(); $t->integer('sort')->default(0); $t->timestamps(); });
  Schema::create('customers', function(Blueprint $t) { $t->id(); $t->string('name'); $t->string('type')->default('individual'); $t->string('email')->nullable()->index(); $t->string('phone'); $t->string('company')->nullable(); $t->string('document')->nullable(); $t->text('address')->nullable(); $t->string('city')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
  Schema::create('leads', function(Blueprint $t) { $t->id(); $t->string('name'); $t->string('phone'); $t->string('email')->nullable(); $t->string('company')->nullable(); $t->string('document')->nullable(); $t->string('city')->nullable(); $t->foreignId('service_id')->nullable()->constrained('contents')->nullOnDelete(); $t->foreignId('status_id')->constrained('lead_statuses')->restrictOnDelete(); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $t->text('message'); $t->string('priority')->default('normal'); $t->string('contact_preference')->default('whatsapp'); $t->string('source')->default('site'); $t->json('attribution')->nullable(); $t->string('consent_version'); $t->timestamp('consented_at'); $t->timestamp('last_interaction_at')->nullable(); $t->timestamps(); });
  Schema::create('lead_interactions', function(Blueprint $t) { $t->id(); $t->foreignId('lead_id')->constrained()->cascadeOnDelete(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->text('message'); $t->timestamps(); });
  Schema::create('service_requests', function(Blueprint $t) { $t->id(); $t->foreignId('customer_id')->constrained()->cascadeOnDelete(); $t->foreignId('service_id')->nullable()->constrained('contents')->nullOnDelete(); $t->foreignId('lead_id')->nullable()->unique()->constrained()->nullOnDelete(); $t->text('description'); $t->text('address')->nullable(); $t->string('priority')->default('normal'); $t->string('status')->default('Aberta'); $t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete(); $t->timestamp('scheduled_at')->nullable(); $t->text('notes')->nullable(); $t->timestamps(); });
  Schema::create('media', function(Blueprint $t) { $t->id(); $t->foreignId('lead_id')->constrained()->cascadeOnDelete(); $t->string('path'); $t->string('name'); $t->string('mime'); $t->timestamps(); });
  Schema::create('settings', function(Blueprint $t) { $t->string('key')->primary(); $t->text('value')->nullable(); });
  Schema::create('audit_logs', function(Blueprint $t) { $t->id(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action'); $t->string('entity'); $t->unsignedBigInteger('entity_id')->nullable(); $t->timestamps(); });
 }
 public function down(): void { foreach(['audit_logs','settings','media','service_requests','lead_interactions','leads','customers','lead_statuses','contents'] as $table) Schema::dropIfExists($table); Schema::table('users',fn(Blueprint $t)=>$t->dropColumn('role')); }
};
