<?php
namespace App\Http\Controllers;
use App\Models\{Lead,LeadStatus,Customer,User};
use App\Support\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Gate,Storage,Cache};
use Illuminate\Validation\Rule;
class AdminController extends Controller {
 public function dashboard(Request $r) {
  Gate::authorize('commercial'); $r->validate(['days'=>'nullable|in:1,7,30,90','from'=>'nullable|date','to'=>'nullable|date|after_or_equal:from']); $from=$r->input('from',now()->subDays((int)$r->input('days',30)-1)->toDateString()); $to=$r->input('to',now()->toDateString());
  $q=Lead::whereBetween('created_at',[$from.' 00:00:00',$to.' 23:59:59']);
  return view('admin.dashboard',['total'=>(clone $q)->count(),'won'=>(clone $q)->whereHas('stage',fn($q)=>$q->where('outcome','won'))->count(),'lost'=>(clone $q)->whereHas('stage',fn($q)=>$q->where('outcome','lost'))->count(),'customers'=>Customer::count(),'recent'=>(clone $q)->with(['service','stage'])->latest()->take(8)->get(),'stages'=>LeadStatus::orderBy('sort')->get(),'counts'=>(clone $q)->selectRaw('status_id, COUNT(*) as total')->groupBy('status_id')->pluck('total','status_id'),'sources'=>(clone $q)->selectRaw('source, COUNT(*) as total')->groupBy('source')->pluck('total','source'),'from'=>$from,'to'=>$to]);
 }
 public function leads(Request $r) { Gate::authorize('commercial'); $q=Lead::with(['service','stage'])->latest(); if($r->filled('q')) $q->where(fn($q)=>$q->where('name','like','%'.request('q').'%')->orWhere('company','like','%'.request('q').'%')); if($r->filled('status')) $q->where('status_id',$r->status); return view('admin.leads',['leads'=>$q->paginate(25)->withQueryString(),'stages'=>LeadStatus::orderBy('sort')->get()]); }
 public function kanban() { Gate::authorize('commercial'); return view('admin.kanban',['stages'=>LeadStatus::orderBy('sort')->get(),'leads'=>Lead::with('service')->latest()->get()->groupBy('status_id')]); }
 public function lead(Lead $lead) { Gate::authorize('commercial'); return view('admin.lead',['lead'=>$lead->load(['service','stage','interactions.user']),'stages'=>LeadStatus::orderBy('sort')->get(),'users'=>User::whereIn('role',['admin','attendant'])->get(),'media'=>DB::table('media')->where('lead_id',$lead->id)->get()]); }
 public function updateLead(Request $r,Lead $lead) { Gate::authorize('commercial'); $data=$r->validate(['status_id'=>'sometimes|required|exists:lead_statuses,id','priority'=>'sometimes|required|in:normal,high,urgent','assigned_to'=>['nullable',Rule::exists('users','id')->whereIn('role',['admin','attendant'])]]); DB::transaction(function() use($lead,$data) { $old=$lead->status_id; $lead->update($data+['last_interaction_at'=>now()]); $lead->interactions()->create(['user_id'=>auth()->id(),'message'=>$old!=$lead->status_id ? 'Etapa alterada para '.$lead->stage->name.'.' : 'Responsável ou prioridade atualizados.']); Company::audit('updated','lead',$lead->id); }); return $r->expectsJson() ? response()->json(['ok'=>true]) : back()->with('success','Lead atualizado.'); }
 public function note(Request $r,Lead $lead) { Gate::authorize('commercial'); $data=$r->validate(['message'=>'required|string|max:5000']); $lead->interactions()->create($data+['user_id'=>auth()->id()]); $lead->update(['last_interaction_at'=>now()]); Company::audit('interaction','lead',$lead->id); return back()->with('success','Interação registrada.'); }
 public function convert(Request $r,Lead $lead) { Gate::authorize('commercial'); $r->validate(['customer_id'=>'nullable|exists:customers,id']); DB::transaction(function() use($lead,$r) { $lead=Lead::lockForUpdate()->findOrFail($lead->id); if($lead->customer_id) return; $customer=$r->filled('customer_id') ? Customer::findOrFail($r->customer_id) : ($lead->email ? Customer::where('email',$lead->email)->first() : Customer::where('phone',$lead->phone)->first()); $customer ??= Customer::create($lead->only(['name','email','phone','company','document','city'])); $lead->update(['customer_id'=>$customer->id,'status_id'=>LeadStatus::where('outcome','won')->firstOrFail()->id]); DB::table('service_requests')->insert(['lead_id'=>$lead->id,'customer_id'=>$customer->id,'service_id'=>$lead->service_id,'description'=>$lead->message,'priority'=>$lead->priority,'created_at'=>now(),'updated_at'=>now()]); $lead->interactions()->create(['user_id'=>auth()->id(),'message'=>'Convertido em cliente. Solicitação de serviço criada.']); Company::audit('converted','lead',$lead->id); }); return back()->with('success','Cliente e solicitação vinculados com sucesso.'); }
 public function deleteLead(Lead $lead) { Gate::authorize('administration'); $paths=DB::table('media')->where('lead_id',$lead->id)->pluck('path'); DB::transaction(function() use($lead){ Company::audit('deleted','lead',$lead->id); $lead->delete(); }); Storage::disk('local')->delete($paths->all()); return redirect('/admin/leads')->with('success','Lead e anexos excluídos.'); }
 public function download(int $id) { Gate::authorize('commercial'); $file=DB::table('media')->find($id); abort_unless($file,404); return Storage::disk('local')->download($file->path,$file->name,['X-Content-Type-Options'=>'nosniff']); }
 public function customers(Request $r) { Gate::authorize('commercial'); return view('admin.customers',['customers'=>Customer::when($r->q,fn($q)=>$q->where('name','like','%'.$r->q.'%'))->latest()->paginate(20)]); }
 public function customerStore(Request $r) { Gate::authorize('commercial'); $data=$r->validate(['name'=>'required|string|max:150','phone'=>'required|string|max:30','email'=>'nullable|email|max:190','company'=>'nullable|string|max:190','city'=>'nullable|string|max:150','type'=>'required|in:individual,company','document'=>'nullable|string|max:30','address'=>'nullable|string|max:1000','notes'=>'nullable|string|max:5000']); $c=Customer::create($data); Company::audit('created','customer',$c->id); return back()->with('success','Cliente cadastrado.'); }
 public function requests() { Gate::authorize('commercial'); return view('admin.requests',['requests'=>DB::table('service_requests')->join('customers','customers.id','=','service_requests.customer_id')->select('service_requests.*','customers.name')->latest('service_requests.created_at')->paginate(20)]); }
 public function requestUpdate(Request $r,int $id) { Gate::authorize('commercial'); $data=$r->validate(['status'=>'required|in:Aberta,Em atendimento,Concluída,Cancelada']); abort_unless(DB::table('service_requests')->where('id',$id)->exists(),404); DB::table('service_requests')->where('id',$id)->update($data+['updated_at'=>now()]); Company::audit('updated','service_request',$id); return back()->with('success','Solicitação atualizada.'); }
 public function settings() { Gate::authorize('administration'); return view('admin.settings',['settings'=>Company::all(),'users'=>User::all(),'stages'=>LeadStatus::orderBy('sort')->get(),'logs'=>DB::table('audit_logs')->latest()->limit(30)->get()]); }
 public function saveSettings(Request $r) { Gate::authorize('administration'); $data=$r->validate(['name'=>'required|string|max:100','email'=>'nullable|email|max:190','whatsapp'=>'nullable|regex:/^[0-9+ ()-]{8,25}$/','phone'=>'nullable|string|max:30','address'=>'nullable|string|max:500','hours'=>'nullable|string|max:200','hero_title'=>'required|string|max:150','hero_text'=>'required|string|max:500','footer'=>'nullable|string|max:500']); foreach($data as $key=>$value) DB::table('settings')->updateOrInsert(['key'=>$key],['value'=>$value]); Cache::forget('company'); Company::audit('updated','settings'); return back()->with('success','Configurações salvas.'); }
 public function userStore(Request $r) { Gate::authorize('administration'); $data=$r->validate(['name'=>'required|string|max:150','email'=>'required|email|unique:users|max:190','password'=>'required|string|min:12','role'=>'required|in:admin,attendant,editor']); $user=User::create($data); Company::audit('created','user',$user->id); return back()->with('success','Usuário criado.'); }
 public function stageStore(Request $r) { Gate::authorize('administration'); $data=$r->validate(['name'=>'required|string|max:60|unique:lead_statuses','sort'=>'required|integer|min:0|max:100','color'=>'required|regex:/^#[0-9a-fA-F]{6}$/']); LeadStatus::create($data); return back()->with('success','Etapa adicionada.'); }
}
